##API Keys


##EPC API

###
# You require a registered account to use this API, and all requests to this API must be authenticated to your account using HTTP Basic Auth. To do this we use a Base64-encoded account identifier composed of your email address and api-key.
# 
# Your Base64-encoded authentication token is:
#   
#   YS5kZW5uZXR0QHVjbC5hYy51azozYTlmM2ZjM2Q2NWQxODJhZGI0Y2FiZDYwZTdjNjFkNDJmMTgzN2Q0
# This token must then be included in the HTTP Authorization header on every API request with the Basic authentication scheme, for example:
#   
#   Both of these tokens are used to authenticate you, so you should take measures to ensure you do not share them publicly, e.g by avoiding commiting them into public source code repositories, or storing them in the source of a publicly accessible website.
# 
# Authorization: Basic YS5kZW5uZXR0QHVjbC5hYy51azozYTlmM2ZjM2Q2NWQxODJhZGI0Y2FiZDYwZTdjNjFkNDJmMTgzN2Q0
# Assuming you have already registered, you should have received an email containing your API key.
# 
# This token is generated by Base64-encoding the string a.dennett@ucl.ac.uk:3a9f3fc3d65d182adb4cabd60e7c61d42f1837d4 which is the concatenation of your email address a.dennett@ucl.ac.uk with the separator : and your api-key 3a9f3fc3d65d182adb4cabd60e7c61d42f1837d4.

epc_user <- "a.dennett@ucl.ac.uk"
epc_api_key <- "3a9f3fc3d65d182adb4cabd60e7c61d42f1837d4"
epc_auth_token <- "YS5kZW5uZXR0QHVjbC5hYy51azozYTlmM2ZjM2Q2NWQxODJhZGI0Y2FiZDYwZTdjNjFkNDJmMTgzN2Q0"
epc_auth <- "Basic YS5kZW5uZXR0QHVjbC5hYy51azozYTlmM2ZjM2Q2NWQxODJhZGI0Y2FiZDYwZTdjNjFkNDJmMTgzN2Q0"

###OS Open Data API

os_auth <- "VExPojL0AMK9qvSwwKUc3g3DZKliugLQ"
